//import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

 
    // 🌟 ԻՍՊՐԱՎԼԵՆՈ: Հեռացրել ենք խափանվող ! նշանը և ավելացրել անվտանգ ֆեյլբեք
  static AppLocalizations of(BuildContext context) {
    final instance = Localizations.of<AppLocalizations>(context, AppLocalizations);
    // Եթե համակարգը դեռ չի հասցրել բեռնել լեզուն, ավտոմատ միացնում ենք դեֆոլտ տարբերակը (ռուսերեն)
    return instance ?? AppLocalizations(const Locale('ru')); 
  }



  // 🌟 Մեր 3 լեզուների բանալիների մատրիցան (Կոդը չծանրացնելու համար՝ ուղիղ հիշողության մեջ)
  static const Map<String, Map<String, String>> _localizedValues = {
    'ru': {
      'home_title': 'Личный Кабинет Шефа',
      
      'search_hint': 'Введите продукт (например: Помидор)',
      'ai_chat_title': 'ИИ Шеф',
      'popular_recipes': 'Популярные рецепты',
'fridge_search': 'Поиск по ингредиентам',
'ai_recipes_generator': 'ИИ-генератор рецептов',
'default_app_title': 'Кулинарный ИИ',
'tab_categories': 'Категории',
'tab_top20': 'Топ-20',
'tab_ai_chef': 'ИИ Шеф',
'cat_hot_dishes': 'Горячие блюда',
'cat_salads': 'Свежие салаты',
'cat_desserts': 'Десерты',
'cat_vegetables': 'Овощи',
'prep_method_title': 'Инструкция по приготовлению:',
'recipe_veiws_label': 'Просмотров:',
'recipe_author_label': 'Автор:',
'recipe_cuisine_label': 'Кухня:',
'recipe_source_label': 'Источник:',
'ctgr_label1': 'Здесь пока нет рецептов этой категории',
'ingr_label1': '⚠️ Положите продукты в холодильник перед вызовом ИИ!',
'fridge_ingr_label': 'Блюдо из холодильника',
'choosed_ingr_label': 'Выбранные ингредиенты:',
'input_ingr_label': 'Введите продукт (например: Помидор)',
'choosed_ingr_lbl': 'Выбранные ингредиенты:',
'fridge_empty_lbl': 'Холодильник пуст',
'srchby_ingr_lbl': 'Найти подходящие рецепты',
'rewrite_recipe_lbl': 'Переписать рецепт через ИИ Шефа',
'notfound_lbl': 'Рецепты не найдены', 
'cookbook_lbl': 'Персональная кулинарная книжка',
'photo_upload_success_lbl': '✅ Аватарка успешно загружена и сохранена в кэш!',
'photo_upload_unsuccess': '❌ Не удалось сохранить изображение в облако Storage',
'current_user_err': '❌ Ошибка: Не удалось определить текущего пользователя.',
'psw_chng_success': '✅ Пароль успешно изменен!',
'server_err_lbl': '❌ Ошибка: Сервер отклонил запрос.',
'ntw_err': '❌ Ошибка сети. Попробуйте позже.',
'prsn_cab':'Личный Кабинет Шефа',
'lng_slct_lbl': 'Выбор языка приложения',
'slct_algns': 'Мои кулинарные ограничения (Аллергены):',
'lactose_lbl': '🥛 Непереносимость Лактозы',
'prtn_lbl': '🌾 Чувствительность к белкам животного происхождения',
'gluten_lbl':'🌾 Чувствительность к Глютену',
'nut_lbl': '🥜 Глубокая аллергия на Орехи',
'fish_lbl':'🌾 Чувствительность к рыбе и морепродуктам',
'psw_chng_lbl':'Изменить пароль',
'prf_scrt_lbl': 'Безопасность профиля',
'prf_scrt_lbl2':'Безопасность учетной записи',
'new_psw_lbl': 'Введите новый пароль',
'input_psw_lbl':'Введите пароль',
'smb_qty_lbl':'Минимум 6 символов',
'upd_psw_lbl':'Обновить пароль',
'myrcp_lbl': 'Мои рецепты в базе',
'admin_lbl': 'Панель администратора',
'inbox_lbl':'Просмотр входящих обращений и отправка ответов поварам',
'ask_sprt_lbl':'Обратиться к администрации',
'logout_lbl':'Выйти из профиля',
'ntw_err2': '❌ Ошибка сохранения на сервере! Проверьте сеть.',
'descrpt_lbl':'Опишите вашу техническую проблему или предложение:',
'msg_lbl':'Напишите текст обращения...',
'ok_lbl':'ok',
'msg_rcv_lbl':'✅ Обращение доставлено на server!' ,
'send_msg_lbl':'Отправить обращение',
'your_rqst_lbl':'Вы спросили:',
'sprt_answ_lbl':'Ответ техподдержки:',
'wait_answ_lbl':'Ожидает ответа',
'my_ktchn_lbl':'Моя Кулинария',
'my_ckbk_lbl':'Сборник моих рецептов',
'add_rcp_lbl':'Добавить новый рецепт',
'attn_msg_lbl':'Вы уверены, что хотите навсегда удалить этот рецепт? Это действие нельзя отменить.',
'delete_rcp_lbl':'Удаление рецепта',
'discard_chng_lbl':'Отмена',
'dlt_csc_lbl':'🎉 Рецепт успешно удален!',
'dlt_unscs_lbl':'❌ Не удалось удалить рецепт',
'slct_lbl':'Указать',
'my_ckbk_lbl2': 'Мой Сборник',
'attn_msg_lbl2':'Вы еще не добавили ни одного рецепта.',
'dlt_rcp_lbl':'Удалить этот рецепт навсегда',
'recipe_adtnl_img_label':'Дополнительные фото блюда:',
'attn_msg_lbl3':'Можно добавить максимум 3 дополнительные фотографии.',
'slct_ingr_lbl':'❌ Добавьте хотя бы один ингредиент!',
'new_rcp_lbl2':'Новый рецепт',
'fill_rcp_data_lbl':'Заполните данные вашего блюда:',
'dish_title_lbl':'Название блюда *',
'input_title_lbl':'Введите название',
'rcp_author_lbl':'Автор рецепта',
 'rcp_cuisine_lbl':'Национальная или интернациональная кухня',
 'rcp_source_lbl':'Источник (Ссылка на сайт первоисточника)',
'rcp_nscr_lbl':'Необязательно',
'rcp_ctgr_lbl':'Категория блюда',
'main_pht_lbl':'Ссылка на основное фото (URL) *',
'upld_pht_lbl':'Загрузить фото с устройства',
'pht_upld_scs_lbl':'✅ Фото блюда успешно загружено в облако!',
'adtnl_pht_lbl2':'Дополнительное фото',
'upld_adtnl_pht_lbl': 'Загрузить дополнительное фото',
'upld_adtnl_pht_lbl2':'Добавить еще фото (Макс. 3)',
'ingr_srch_lbl':'Поиск ингредиента...',
'instr_lbl':'Способ приготовления / Инструкции *',
'describe_lbl':'Опишите шаги приготовления блюда',
'adtnl_prpt_lbl':'⚙️ Системные мета-поля (Будут скрыты в JSON):',
'id_lbl':'• id: генерируется автоматически на стороне БД', 
'date_lbl':'• дата ввода: автоматически (NOW())',
 'views_lbl2':'• viewscount: инициализируется как 0',
 'upld_rcp_lbl':'Опубликовать рецепт',
'rcp_edit_lbl':'Редактирование рецепта',
'pht_upld_unscs_lbl':'❌ Не удалось сохранить изображение в Storage',
'attn_msg_lbl5':'⚠️ Название и инструкции не могут быть пустыми',
'scs_edit_lbl':'✅ Рецепт успешно обновлен!',
'unscs_edit_lbl': '❌ Не удалось обновить рецепт',
'save_edit_lbl': 'Сохранить изменения',
'ai_chat_title_lbl':'Консультация ИИ Шеф-Повара',
'ask_ai_lbl':'Задайте ИИ-Шефу любой кулинарный вопрос!\nНапример: "Что приготовить из кабачков?"',
 'ask_ai_lbl2': 'Спрашивайте',
 'origin_rcp_lbl':'Оригинальный рецепт:',
 'your_alrgn_lbl': '⚠️ Ваши аллергены:',
 'rewrt_rcp_lbl': 'Переписать рецепт без аллергенов',
 'err_type1_lbl':'❌ Не удалось открыть страницу оплаты',
 'err_type2_lbl':'❌ Ошибка шлюза Cryptomus. Проверьте API ключи.',
      'vip_screen_title': 'PREMIUM VIP Подписка',
      'vip_status_active': 'Ваш VIP статус: АКТИВЕН',
      'vip_status_inactive': 'Ваш VIP статус: НЕАКТИВЕН',
      'vip_status_desc': 'Активируйте доступ, чтобы разблокировать безлимитный ИИ Помощник и Умный Чат без ограничений.',
      'vip_choose_plan': 'Выберите тарифный план:',
      'plan_monthly_title': 'Ежемесячно',
      'plan_monthly_desc': 'Доступ ко всем ИИ функциям на 30 дней',
      'plan_yearly_title': 'Ежегодно (Выгодно)',
      'plan_yearly_desc': 'Экономия 33%! Доступ на 12 месяцев',
      'stripe_disclaimer': '* Оплата безопасно обрабатывается международной системой Stripe. Списание происходит раз в месяц или год. Вы можете отменить подписку в любой момент в настройках профиля.',
      'btn_my_wallet': 'Управление PREMIUM VIP',
      'btn_ai_translate': 'Переводчик',
      'dlt_scs_lbl': 'Рецепт успешно удален',
      



    },
    'en': {
      'home_title': 'Chef Personal Account',
      
      'search_hint': 'Enter product (e.g. Tomato)',
      'ai_chat_title': 'AI Chef',
       'popular_recipes': 'Popular recipes',
'fridge_search': 'Search recipes by ingredients',
'ai_recipes_generator': 'Recipes AI generator',
'default_app_title': 'Culinary AI',
'tab_categories': 'Categories',
'tab_top20': 'Top-20',
'tab_ai_chef': 'AI Chef',
'cat_hot_dishes': 'Hot dishes',
'cat_salads': 'Fresh salads',
'cat_desserts': 'Desserts',
'cat_vegetables': 'Vegetables',
'prep_method_title': 'Cooking instruction:',
'recipe_veiws_label': 'Viewscount:',
'recipe_author_label': 'Author:',
'recipe_cuisine_label': 'Kitchen:',
'recipe_source_label': 'Source:',
'ctgr_label1':'There are no recipes in this category yet',
'ingr_label1': '⚠️ Put the groceries in the fridge before calling the AI!',
'fridge_ingr_label': 'From fridge',
'choosed_ingr_label': 'Selected ingredients:',
'input_ingr_label': 'Enter an ingredient name, for example: tomato)',
'choosed_ingr_lbl': 'Selected Ingredients:',
'fridge_empty_lbl': 'The fridge is empty',
'srchby_ingr_lbl': 'Searching for suitable recipes',
'rewrite_recipe_lbl': 'Rewrite the recipe through the AI ​​Chef',
'notfound_lbl': 'No recipes found', 
'cookbook_lbl': 'Personal cookbook',
'photo_upload_success_lbl': '✅ The photo successgully uploded and cached!',
'photo_upload_unsuccess': '❌ Unsuccessful upload',
'current_user_err': '❌ Error: The current user had not been determinated.',
'psw_chng_success': '✅ The password changed successfully!',
'server_err_lbl': '❌ Error: The server rejected the request.',
'ntw_err': '❌ Network error. Try later.',
'prsn_cab':'Dashboard of Chef',
'lng_slct_lbl': 'Choose the language:',
'slct_algns': 'My dietary restrictions (Allergens):',
'lactose_lbl': '🥛 Lactose Intolerance',
'prtn_lbl': '🌾 Sensitivity to animal proteins',
'gluten_lbl':'🌾 Gluten sensitivity',
'nut_lbl': '🥜 Severe nut allergy',
'fish_lbl':'🌾 Sensitivity to fish and seafood',
'psw_chng_lbl':'Change password',
'prf_scrt_lbl': 'Profile security',
'prf_scrt_lbl2':'Account security',
'new_psw_lbl': 'Enter new password',
'input_psw_lbl':'Enter password',
'smb_qty_lbl':'Minimum 6 characters',
'upd_psw_lbl':'Update password',
'myrcp_lbl': 'My recipes in the database',
'admin_lbl': 'Administrator panel',
'inbox_lbl':'View incoming inquiries and reply to chefs',
'ask_sprt_lbl':'Contact administration',
'logout_lbl':'Log out',
'ntw_err2': '❌ Server save error! Check your network connection.',
'descrpt_lbl':'Describe your technical issue or suggestion:',
'msg_lbl':'Enter your message...',
'ok_lbl':'OK',
'msg_rcv_lbl':'✅ Message delivered to the server!' ,
'send_msg_lbl':'Send message',
'your_rqst_lbl':'You asked:',
'sprt_answ_lbl':'Support response:',
'wait_answ_lbl':'Awaiting response',
'my_ktchn_lbl':'My Cooking',
'my_ckbk_lbl':'My Recipe Collection',
'add_rcp_lbl':'Add a new recipe',
'attn_msg_lbl':'Are you sure you want to permanently delete this recipe? This action cannot be undone.',
'delete_rcp_lbl':'Delete recipe',
'discard_chng_lbl':'Cancel',
'dlt_csc_lbl':'🎉 Recipe successfully deleted!',
'dlt_unscs_lbl':'❌ Failed to delete recipe',
'slct_lbl':'Specify',
'my_ckbk_lbl2':'My Collection',
'attn_msg_lbl2':'You haven not added any recipes yet.',
'dlt_rcp_lbl':'Delete this recipe permanently',
'recipe_adtnl_img_label':'Additional dish photos:',
'attn_msg_lbl3':'You can add a maximum of 3 additional photos.',
'slct_ingr_lbl':'❌ add at least one ingredient!',
'new_rcp_lbl2':'New Recipe',
'fill_rcp_data_lbl':'Fill in your dish details:',
'dish_title_lbl':'Dish Name *',
'input_title_lbl':'Enter Title',
'rcp_author_lbl':'Recipe Author',
'rcp_cuisine_lbl':'National or International Cuisine',
'rcp_source_lbl':'Source (Link to the original source website)',
'rcp_nscr_lbl':'Optional',
'rcp_ctgr_lbl':'Dish Category',
'main_pht_lbl':'Link to Further Photo (URL) *',
'upld_pht_lbl':'Upload Photo from device',
'pht_upld_scs_lbl':'✅ Dish photo successfully uploaded to the cloud!',
'adtnl_pht_lbl2':'Additional photo',
'upld_adtnl_pht_lbl': 'Upload additional photos',
'upld_adtnl_pht_lbl2':'Add more photos (Max 3)',
'ingr_srch_lbl':'Search for ingredient...',
'instr_lbl':'Cooking method / Instructions *',
'describe_lbl':'Describe the cooking steps',
'adtnl_prpt_lbl':'⚙️ System metafields (Will be hidden in JSON):',
'id_lbl':'• id: automatically move to the DB side',
'date_lbl':'• date input: automatically (NOW())',
'views_lbl2':'• Number of views: conceptualized as 0',
'upld_rcp_lbl':'Publish recipe',
'rcp_edit_lbl':'Edit recipe',
'pht_upld_unscs_lbl':'❌ Failed to save image to Storage',
'attn_msg_lbl5':'⚠️ Title and instructions cannot be empty',
'scs_edit_lbl':'✅ Recipe successfully updated!',
'unscs_edit_lbl': '❌ Failed to update recipe',
'save_edit_lbl': 'Save changes',
'ai_chat_title_lbl': 'Chat with the AI ​​Chef',
'ask_ai_lbl': 'Ask the AI ​​Chef any culinary question!\nFor example: "What to make with zucchini?"',
'ask_ai_lbl2': 'Question',
'origin_rcp_lbl':'Original recipe',
 'your_alrgn_lbl': '⚠️ Your allergens:',
 'rewrt_rcp_lbl': 'Adapt this recipe for allergies',
      'vip_screen_title': 'PREMIUM VIP Subscription',
      'vip_status_active': 'Your VIP Status: ACTIVE',
      'vip_status_inactive': 'Your VIP Status: INACTIVE',
      'vip_status_desc': 'Activate access to unlock unlimited AI Assistant and Smart Chat without constraints.',
      'vip_choose_plan': 'Choose your subscription plan:',
      'plan_monthly_title': 'Monthly Plan',
      'plan_monthly_desc': 'Full AI access for 30 days',
      'plan_yearly_title': 'Yearly Plan (Save Big)',
      'plan_yearly_desc': 'Save 33%! Full access for 12 months',
      'stripe_disclaimer': '* Payments are securely processed by Stripe. Subscription automatic renewals can be canceled at any time in your profile settings.',
      'btn_my_wallet': 'Manage PREMIUM VIP',
      'btn_ai_translate': 'Tranlator',
      'dlt_scs_lbl': 'Recipe successfully deleted',
},

    'hy': {
      'home_title': 'Շեֆի Անձնական Կաբինետ',
      
      'search_hint': 'Մուտքագրեք մթերքը (օր.՝ Լոլիկ)',
      'ai_chat_title': 'ԱԲ խոհարար',
       'popular_recipes': 'Պոպուլյար բաղադրատոմսեր',
'fridge_search': 'Փնտրել ըստ բաղադրիչների',
'ai_recipes_generator': 'Բաղադրատոմսերի ԱԲ գեներատոր',
'default_app_title': 'Խոհարարական ԱԲ',
'tab_categories': 'Կատեգորիաներ',
'tab_top20': 'Թոփ-20',
'tab_ai_chef': 'ԱԲ Խոհարար',
'cat_hot_dishes': 'Տաք ուտեստներ',
'cat_salads': 'Թարմ սալաթներ',
'cat_desserts': 'Դեսերտներ',
'cat_vegetables': 'Բանջարեղեն',
'prep_method_title': 'Պատրաստման եղանակ:',
'recipe_veiws_label': 'Դիտումներ:',
'recipe_author_label': 'Հեղինակ:',
'recipe_cuisine_label': 'Խոհանոց:',
'recipe_source_label': 'Աղբյուր:',
'ctgr_label1':'Այստեղ դեռ չկան տվյալ կատեգորիայի բաղադրատոմսեր',
'ingr_label1': '⚠️ ԱԲ֊ին դիմելուց առաջ ընտրեք բաղադրիչները',
'fridge_ingr_label': 'Ինչ կա սառնարանում',
'choosed_ingr_label': 'Ընտրած բաղադրիչները:',
'input_ingr_label': 'Ընտրեք բաղադրիչները, օրինակ՝ լոլիկ',
'choosed_ingr_lbl': 'Ընտրած բաղադրիչները:',
'fridge_empty_lbl': 'Սառնարանը դատարկ է',
'srchby_ingr_lbl': 'Համապատասխան բաղադրատոմսեր',
'rewrite_recipe_lbl': 'ԱԲ բաղադրատոմս',
'notfound_lbl': 'Բաղադրատոմսեր չեն գտնվել', 
'cookbook_lbl': 'Անձնական խոհարարական գիրք',
'photo_upload_success_lbl': '✅ Ավատարը հաջողությամբ վերբեռնվեց և պահպանվեց քեշում!',
'photo_upload_unsuccess': '❌ Չհաջողվեց պահպանել պատկերը ամպային պահեստում',
'current_user_err': '❌ Սխալ. Հնարավոր չէ որոշել ներկայիս օգտատիրոջը',
'psw_chng_success': '✅ Գաղտնաբառը հաջողությամբ փոխվեց!',
'server_err_lbl': '❌ Սխալ. Սերվերը մերժեց հարցումը',
'ntw_err': '❌ Ցանցային սխալ. Խնդրում ենք կրկին փորձել ավելի ուշ։',
'prsn_cab':'Խոհարարի անձնական հաշիվը',
'lng_slct_lbl': 'Հավելվածի լեզվի ընտրություն ',
'slct_algns': 'Իմ խոհարարական սահմանափակումները (ալերգեններ):',
'lactose_lbl': '🥛 Լակտոզայի անհանդուրժողականություն',
'prtn_lbl': '🌾 Կենդանիների սպիտակուցի նկատմամբ զգայունություն',
'gluten_lbl': '🌾 Գլյուտենի նկատմամբ զգայունություն',
'nut_lbl': '🥜 Ծանր ընկույզի ալերգիա',
'fish_lbl': '🌾 Ձկան և ծովամթերքի',
'psw_chng_lbl':'Փոխել գաղտնաբառը',
'prf_scrt_lbl':'Պրոֆիլի անվտանգություն',
'prf_scrt_lbl2':'Պրոֆիլի անվտանգություն',
'new_psw_lbl':'Մուտքագրեք նոր գաղտնաբառը',
'input_psw_lbl':'Մուտքագրեք գաղտնաբառը',
'smb_qty_lbl':'Նվազագույնը 6 նիշ',
'upd_psw_lbl':'Թարմացրեք գաղտնաբառը',
'myrcp_lbl':'Իմ բաղադրատոմսերը տվյալների բազայում',
'admin_lbl':'Ադմինիստրատորի վահանակ',
'inbox_lbl':'Դիտեք մուտքային հարցումները և ուղարկեք պատասխաններ խոհարարներին',
'ask_sprt_lbl':'Կապվեք ադմինիստրացիայի հետ',
'logout_lbl':'Ելք պրոֆիլից',
'ntw_err2': '❌ Սխալ սերվերում պահպանելիս! Ստուգեք ձեր ցանցը։',
'descrpt_lbl':'Նկարագրեք ձեր տեխնիկական խնդիրը կամ առաջարկը՝',
'msg_lbl':'Գրեք ձեր հարցումը...',
'ok_lbl':'ok',
'msg_rcv_lbl':'✅ Հարցումը ուղարկվել է սերվերին!' ,
'send_msg_lbl':'Ուղարկել հարցումը',
'your_rqst_lbl':'Դուք հարցրել եք՝',
'sprt_answ_lbl':'Տեխնիկական աջակցության պատասխանը՝',
'wait_answ_lbl':'Սպասում եմ պատասխանի',
'my_ktchn_lbl':'Իմ խոհանոցը',
'my_ckbk_lbl':'Իմ բաղադրատոմսերի գրքույկ',
'add_rcp_lbl':'Ավելացնել նոր բաղադրատոմս',
'attn_msg_lbl':'Համոզվա՞ծ եք, որ ցանկանում եք ընդմիշտ ջնջել այս բաղադրատոմսը։ Բաղադրատոմսը չի կարող վերականգնվել։',
'delete_rcp_lbl':'Ջնջել բաղադրատոմսը',
'discard_chng_lbl':'Չեղարկել',
'dlt_csc_lbl':'🎉 Բաղադրատոմսը հաջողությամբ ջնջվել է!',
'dlt_unscs_lbl':'❌ Չհաջողվեց ջնջել բաղադրատոմսը',
'slct_lbl':'Նշել',
'my_ckbk_lbl2':'Իմ բաղադրատոմսեր',
'attn_msg_lbl2':'Դուք դեռ որևէ բաղադրատոմս չեք ավելացրել։',
'dlt_rcp_lbl':'Ջնջել այս բաղադրատոմսը ընդմիշտ',
'recipe_adtnl_img_label':'Լրացուցիչ լուսանկարներ՝',
'attn_msg_lbl3':'Կարող եք ավելացնել առավելագույնը 3 լրացուցիչ լուսանկար։',
'slct_ingr_lbl':'❌ ավելացնել առնվազն մեկ բաղադրիչ!',
'new_rcp_lbl2':'Նոր բաղադրատոմս',
'fill_rcp_data_lbl':'Լրացրեք ձեր ուտեստի մանրամասները',
'dish_title_lbl':'Ուտեստի անվանումը *',
'input_title_lbl':'Մուտքագրեք վերնագիրը',
'rcp_author_lbl':'Բաղադրատոմսի հեղինակ',
'rcp_cuisine_lbl':'Ազգային կամ միջազգային խոհանոց',
'rcp_source_lbl':'Սկզբնաղբյուր (հղում)',
'rcp_nscr_lbl':'Ըստ ցանկության',
'rcp_ctgr_lbl':'Ուտեստի կատեգորիա',
'main_pht_lbl':'Հիմնական լուսանկար (URL) *',
'upld_pht_lbl':'Բեռնել լուսանկարը սարքից',
'pht_upld_scs_lbl':'✅ Ուտեստի լուսանկարը հաջողությամբ բեռնվել է ամպ!',
'adtnl_pht_lbl2':'Լրացուցիչ լուսանկար',
'upld_adtnl_pht_lbl': 'Բեռնել լրացուցիչ լուսանկարներ',
'upld_adtnl_pht_lbl2':'Ավելացնել ավելի շատ լուսանկարներ (առավելագույնը 3)',
'ingr_srch_lbl':'Փնտրել բաղադրիչ...',
'instr_lbl':'Պատրաստման եղանակ *',
'describe_lbl':'Նկարագրել պատրաստման քայլերը',
'adtnl_prpt_lbl':'⚙️ Համակարգի մետադաշտեր (Կթաքցվեն JSON-ում):',
'id_lbl':'• id: ավտոմատ կերպով տեղափոխվել տվյալների բազայի կողմ',
'date_lbl':'• ամսաթվի մուտքագրում: ավտոմատ կերպով (NOW())',
'views_lbl2':'• Դիտումների քանակը՝ հայեցակարգված է որպես 0',
'upld_rcp_lbl':'Հրապարակել բաղադրատոմսը',
'rcp_edit_lbl':'Խմբագրել բաղադրատոմսը',
'pht_upld_unscs_lbl':'❌ Չհաջողվեց պահպանել պատկերը պահեստում',
'attn_msg_lbl5':'⚠️ Վերնագիրը և հրահանգները չեն կարող դատարկ լինել',
'scs_edit_lbl':'✅ Բաղադրատոմսը հաջողությամբ թարմացվեց!',
'unscs_edit_lbl': '❌ Չհաջողվեց թարմացնել բաղադրատոմսը',
'save_edit_lbl': 'Պահպանել փոփոխությունները',
'ai_chat_title_lbl': 'Հարցրեք ԱԲ֊ին խոհարարությունից',
'ask_ai_lbl': 'Տվեք ԱԲ խոհարարին ցանկացած խոհարարական հարց!\nՕրինակ՝ «Ի՞նչ պատրաստել դդմիկից»',
'ask_ai_lbl2': 'Հարց',
'origin_rcp_lbl':'Բաղադրատոմսի բնօրինակ',
 'your_alrgn_lbl': '⚠️ Ձեր ալերգենները:',
 'rewrt_rcp_lbl': 'Բաղադրատոմսը՝ առանց ալերգենների',

      'vip_screen_title': 'PREMIUM VIP Բաժանորդագրություն',
      'vip_status_active': 'Ձեր VIP Կարգավիճակը. ԱԿՏԻՎ Է',
      'vip_status_inactive': 'Ձեր VIP Կարգավիճակը. ԱԿՏԻՎ ՉԷ',
      'vip_status_desc': 'Ակտիվացրեք հասանելիությունը՝ անսահմանափակ ԻԻ Օգնականից և Խելացի Չատից առանց արգելքների օգտվելու համար։',
      'vip_choose_plan': 'Ընտրեք սակագնային պլանը.',
      'plan_monthly_title': 'Ամսական Պլան',
      'plan_monthly_desc': 'Լիարժեք ԻԻ հասանելիություն 30 օրով',
      'plan_yearly_title': 'Տարեկան Պլան (Խնայողությամբ)',
      'plan_yearly_desc': 'Խնայեք 33%: Լիարժեք հասանելիություն 12 ամսով',
      'stripe_disclaimer': '* Վճարումները ապահով կերպով իրականացվում են Stripe միջազգային համակարգով։ Բաժանորդագրությունը կարող եք չեղարկել ցանկացած պահի պրոֆիլի կարգավորումներում։',
      'btn_my_wallet': 'Կառավարել PREMIUM VIP-ը',
      'btn_ai_translate': 'Թարգմանիչ',
      'dlt_scs_lbl': 'Բաղադրատոմսը հեռացված է',
      



    }
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['ru', 'en', 'hy'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
